Concordium/concordium-reference-wallet-android

app/src/main/res/values/strings.xml

Issue 54
https://github.com/Concordium/concordium-reference-wallet-android/issues/54
Text changed. If user tries to change password/passcode when there is a failed/pending identity.
I have got the new text from Jens Ager Sørensen.

Changed text alterpassword_non_finalised_items

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/concordium/wallet/ui/more/export/ExportActivity.kt
app/src/main/java/com/concordium/wallet/ui/more/export/ExportChooseMethodFragment.kt
app/src/main/java/com/concordium/wallet/ui/more/export/ExportViewModel.kt
app/src/main/res/values/strings.xml

The purpose is to solve issue #70 
Needed to add the manifest permission to write to external storage.
Used Figma design:
https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=60%3A57
I have tested on emulator SDK 26, 27, and 30.
And also tested on real device SDK 32.

Export to local storage

---

app/src/main/java/com/concordium/wallet/AppCore.kt
app/src/main/java/com/concordium/wallet/data/model/BakerPoolInfo.kt
app/src/main/java/com/concordium/wallet/data/model/BakerPoolStatus.kt
app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewFragment.kt
app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewViewModel.kt
app/src/main/res/values/strings.xml

https://github.com/Concordium/concordium-reference-wallet-android/issues/143
Load pool status for each pool used in accounts that are delegating. Check if any of the pools have closed. If so then show a notice about it.
_Remove if not applicable.

Check for removed pools on account overview

---

app/src/main/java/com/concordium/wallet/data/room/Account.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/StakeAmountInputValidator.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterAmountActivity.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterPoolActivity.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationViewModel.kt
app/src/main/res/layout/activity_delegation_registration_amount.xml
app/src/main/res/values/strings.xml

https://github.com/Concordium/concordium-reference-wallet-android/issues/141
Check for too large delegation amounts when changing target pools.
_Remove if not applicable.

Check for too large delegation amounts when changing target pools

---

app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt

Prevent the update of delegation stake to a pool with status "Closed for new".
Test: See #175 
A missing clause in an if statement.
_Remove if not applicable.

CBW-201 (GitHub issue 175)

---

app/build.gradle
app/src/main/java/com/concordium/wallet/data/preferences/AuthPreferences.kt
app/src/main/java/com/concordium/wallet/data/preferences/Preferences.kt
app/src/main/java/com/concordium/wallet/ui/account/common/NewAccountViewModel.kt
app/src/main/java/com/concordium/wallet/ui/auth/login/AuthLoginActivity.kt
app/src/main/java/com/concordium/wallet/ui/auth/login/AuthLoginViewModel.kt
app/src/main/java/com/concordium/wallet/ui/common/delegates/AuthDelegate.kt
app/src/main/java/com/concordium/wallet/ui/identity/identityproviderlist/IdentityProviderListActivity.kt
app/src/main/java/com/concordium/wallet/ui/identity/identityproviderlist/IdentityProviderListViewModel.kt
app/src/main/java/com/concordium/wallet/ui/more/alterpassword/AlterPasswordViewModel.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/recover/PassPhraseRecoverInputFragment.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/recover/PassPhraseRecoverViewModel.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/recover/RecoverWalletActivity.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/recoverprocess/RecoverProcessViewModel.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/setup/PassPhraseViewModel.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/setup/SetupWalletActivity.kt
app/src/main/res/layout/activity_auth_login.xml
app/src/main/res/values/strings.xml
build.gradle

Encrypt the seed and save it securely.
Encrypt seed before saving.
Encrypt already existing seed.
Re-encrypt seed with new password when changing passwords.

Encrypt seed

---

.github/workflows/build+test.yml

The workflow is still run once the branch has been merged to 'main'.

CI: Skip workflow on PRs that only change '.md' files

---

build.gradle

Add ability to gain insight to the dependency structure of Gradle tasks.
Add Gradle plugin `Gradle Task Tree`.

Gradle: Add plugin for printing the dependency tree of a given task

---

.github/workflows/build+test.yml

The APKs are quite big - around 75 MB each and we build 10 different variants (debug and release for 5 different flavors). So we store only the release builds of stagenet, testnet, and mainnet.
There should be a [500 MB](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions) limit, but I haven't seen it take effect yet.

CI: Build APKs and persist them as workflow artifacts

---

.github/workflows/build+test.yml
.github/workflows/build+upload.yml

Reduce the resources usage of the verification workflow in terms of computational resources and persistent storage by not building and uploading artifacts in each run.
Do the upload in a separate workflow that is run manually and has to be run from a tag.

Move upload to separate workflow

---

.github/workflows/build+test.yml
app/build.gradle

The roboelectric runner apparently generates new classes, so including "no location classes" is necessary (which in turn necessitates excluding `jdk.internal.*`).
Included a few other simplifications to the configuration that I found to not change the end result.
The change is prompted by the observation that coverage data wasn't collected for the new tests in https://github.com/Concordium/concordium-reference-wallet-android/pull/203.

CI: Fix coverage collection for tests run by roboelectric

---

app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenActivity.kt
app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenViewModel.kt

Sending a CCD tokens from the CIS-2 flow failed if memo is added to the transaction.
The memo was sent as a plain String, now its is first encoded with CBORUtil and the resulting ByteArray is converted to Hex String. This fixed the issue with the wallet_lib failing.

CIS-2 add memo fix

---

app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt

Fixes adding fungible CIS2 tokens as collectibles. As I understood, if the token metadata has the "unique" flag set to "false", it means that it is a fungible token, but the wallet threats such tokens as collectibles.
- Incorrect setting of `ContractToken.isFungible` field in `TokensViewModel`

Fix adding fungible tokens as collectibles

---

app/src/main/java/com/concordium/wallet/ui/account/accountdetails/AccountDetailsActivity.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensAddAdapter.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/lookfornew/ContractAddressFragment.kt
app/src/main/java/com/concordium/wallet/ui/cis2/lookfornew/LookForNewTokensFragment.kt

Fixing of various issues with new tokens search dialog.
- Fixed opening the dialog on the second page after re-open. Happens when adding tokens from multiple contracts one by one
- Fixed keeping the contract error on dialog re-opening
- Fixed showing previous token list items while new tokens are loading on token selection screen
_Remove if not applicable.

Fix new tokens search dialog issues

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenActivity.kt

Fix an issue where the thumbnail of the wrong token could be shown to the user. This happened exactly when on a token with a thumbnail and then selecting a thumbnail-less token, i.e. the image would not be updated in this case.
- Reload thumbnail even though the thumbnail is not present in the token (as the no image icon is loaded in this case). Note that it is fine to load on a null URL according to the Glide docs (https://bumptech.github.io/glide/doc/getting-started.html#listview-and-recyclerview).

Reload token thumbnails when switching to tokens without a thumbnail

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/data/walletconnect/ParamsDeserializer.kt

The format was emitted by mistake from the a previous version of the client side library `@concordium/wallet-connectors`. The library has been fixed but the wallets retain support for it for backwards compatibility.
The Wallet accepted the format but passed it indiscriminately to the crypto library without doing the appropriate conversion. This resulted in the library call failing without any error being surfaced to the user. Instead the parameters are just not presented on the approval screen. With this commit the conversion is performed right after the schema is parsed to handle it correctly. Ideally error handling should be improved to avoid misleading the user, but as the app is being deprecated, it may not be worth the effort.

WalletConnect: Fix parsing of "broken" schema format

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/cis2/TokensAddAdapter.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt
app/src/main/res/values/strings.xml

This fixes inability to add CIS-2 tokens with corrupted metadata or missing balance. Metadata and balances are loaded asynchronously. In this way, you get the list of tokens pretty fast, and then it fills with extra data. With that, tokens with broken or missing metadata are shown like dummies with no ability to select them, while other tokens, once fully loaded, get the check mark available.
- Skip burnt tokens (with total supply 0) during lookup
- Do not let adding tokens without metadata
- Indicate metadata loading progress in tokens list

More lenient CIS-2 Lookup

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/more/export/ExportAccountKeysViewModel.kt

Incorrect value was written to `environment` for Mainnet and Testnet.
Fix writing incorrect `environment` value to the key export file. Incorrect values was written for Mainnet and Testnet.
- Fix writing incorrect `environment` value to the key export file

Fix use of env name instead of chain for key export

---

app/src/main/java/com/concordium/wallet/data/backend/ProxyBackend.kt
app/src/main/java/com/concordium/wallet/data/backend/repository/ProxyRepository.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/lookfornew/ContractAddressFragment.kt
app/src/main/res/values/strings.xml

This is a second part of [more lenient CIS-2 Lookup](https://concordium.atlassian.net/browse/CBW-1600).
- Load token metadata and balances before showing the list of found tokens
- Filter out tokens with corrupted or missing metadata
- Show "This contract has no valid tokens" if all the contract tokens are invalid
- Get rid of token lookup errors made obsolete by this change (invalid index, invalid metadata, invalid metadata checksum)
Internally:
- Use new fail-proof batch endpoints to fetch metadata and balance info

Load all the info before showing a list of found CIS-2 tokens

---

app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt

This fixes [WAL2-59](https://linear.app/concordium/issue/WAL2-59/it-is-not-possible-to-send-wccd) – inability to send wCCD.
- Fix not saving token contract name after making CIS-2 lookup more lenient

Fix not saving token contract name

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/lookfornew/SelectTokensFragment.kt

Make the search field do the exact token lookup instead of filtering the current list of found tokens, which may be partial. [WAL2-69](https://linear.app/concordium/issue/WAL2-69/not-possible-to-add-tokens-in-android-wallet-in-some-cases)
- Update the "Search by token ID" field logic
- Simplify `updateWithSelectedTokens` which also fixes removing all of added CIS-2 tokens when only unselecting the visible ones when managing

Fix inability to search for CIS-2 token by its ID

---

CHANGELOG.md
app/build.gradle
app/src/main/java/com/concordium/wallet/data/model/ChainParameters.kt
app/src/main/java/com/concordium/wallet/data/model/SimpleFraction.kt
app/src/main/java/com/concordium/wallet/data/model/TransferCost.kt
app/src/main/java/com/concordium/wallet/data/util/TransactionCostCalculator.kt
app/src/main/java/com/concordium/wallet/data/walletconnect/Payload.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenViewModel.kt
app/src/main/java/com/concordium/wallet/ui/transaction/sendfunds/SendFundsViewModel.kt
app/src/main/java/com/concordium/wallet/ui/walletconnect/WalletConnectViewModel.kt

Fix WalletConnect cost estimation failing if the smart contract call parameters are large.
The changes are the same as in https://github.com/Concordium/cryptox-android/pull/26
- Replace asking wallet proxy for transaction cost with local fee estimation for WalletConnect Update transactions

UFT-1398 Fix WalletConnect cost estimation failing

---

app/src/main/java/com/concordium/wallet/data/model/SimpleFraction.kt

The crash was caused by missing Serializable marker on SimpleFraction, introduced with WC cost estimation fix.
- Add missing Serializable marker on SimpleFraction

WAL2-85 Fix crash on validator setup flow
